backend:
  name: git-gateway
  branch: main
  repo: evyataar/Haredim

title: חדשות מהדרין
description: אתר חדשות חצי ברצינות, חצי בריחוק
baseurl: ""  # leave empty for root
url: "https://haredim.netlify.app"
permalink: /:title/
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
