backend:
  name: git-gateway
  branch: main
  repo: evyataar/Haredim

title: חדשות מהדרין
description: אתר חדשות חצי בדיחה, חצי רציני
baseurl: "/Haredim"
url: "https://yourusername.github.io/news-site"
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
include:
  - assets

