backend:
  name: git-gateway
  branch: main
  repo: evyataar/Haredim

title: חדשות מהדרין
description: אתר חדשות חצי בדיחה, חצי רציני
baseurl: ""
url: "https://yourusername.github.io/news-site"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

plugins:
  - jekyll-feed
  - jekyll-seo-tag

