backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: 'he'

collections:
  - name: "posts"
    label: "פוסטים"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "כותרת"
        name: "title"
        widget: "string"
      - label: "כותרת משנה"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "מחבר"
        name: "author"
        widget: "string"
        required: false
      - label: "תאריך"
        name: "date"
        widget: "datetime"
      - label: "תמונה ראשית"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "תוכן"
        name: "body"
        widget: "markdown"
  

